apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping-config
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: shipping
data:
  CART_ENDPOINT: "cart:8080"
  DB_HOST: "mysql"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: roboshop
  name: shipping
  labels:
    project: roboshop
    tier: backend
    component: shipping
spec: 
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      tier: backend
      component: shipping
  template:
    metadata:
      labels:
        project: roboshop
        tier: backend
        component: shipping
    spec:
      containers:
        - name: shipping
          image: devzonefun/shipping:2.1.0
          imagePullPolicy: Always
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          readinessProbe:
            tcpSocket:
              port: 8080
            failureThreshold: 2
            initialDelaySeconds: 15
            periodSeconds: 10

          startupProbe:
            httpGet:
              path: /health
              port: 8080
            failureThreshold: 30
            periodSeconds: 10
        
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            failureThreshold: 2
            periodSeconds: 10
          envFrom:
          - configMapRef:
              name: shipping-config
---
apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: shipping
spec:
  selector:
    project: roboshop
    tier: backend
    component: shipping
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080